main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('quiz', views.index, name='index'),
    path('quiz/<int:question_id>/', views.detail, name='detail'),
    path('quiz/<int:question_id>/results/', views.results, name='results'),
    path('quiz/<int:question_id>/respond/', views.respond, name='respond'),
]

webApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from register import views as v
from main import views as v1
from forum import views as v2
from course import views as v3
from quiz import views as v4

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name="register"),
    path('account/', v1.account, name="account"),
    path('changePassword/', v1.change_password, name='changePassword'),
    path('changeEmail/', v1.email_change, name='changeEmail'),
    path('', include("main.urls")),
    path('', include("django.contrib.auth.urls")),
    path('forum/', v2.forumApp, name='forum'),
    path('addInForum/', v2.addInForum, name='addInForum'),
    path('addInDiscussion/', v2.addInDiscussion, name='addInDiscussion'),
    path('course/', v3.groupApp, name='course'),
    path('addGroup/', v3.addGroup, name='addGroup'),
    path('addInUser/', v3.addInUser, name='addInUser'),
    path('uploadFile/', v3.uploadFile, name='uploadFile'),
    path('materials/', v3.studentGroup, name='studentGroup'),
    path('sendEmail/', v3.sendEmail, name='sendEmail'),
    path('', include("quiz.urls")),
    path('quiz/', v4.index, name='quiz'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
from django.db import models

# Create your models here.
from django.utils import timezone

from course.models import Group


class Question(models.Model):
    group = models.ForeignKey(Group, blank=True, on_delete=models.CASCADE, default=1)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

quiz/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Question, Choice
from course.models import Group, Users


def index(request):
    grup = []
    user = Users.objects.all()
    latest_question_list = Question.objects.order_by('-pub_date')[:5]

    for x in user:
        if request.user.username.strip() == x.username.strip():
            grup.append(x.group)

    for x in Group.objects.all():
        if x.teacher == request.user.first_name + " " + request.user.last_name:
            grup.append(x)

    count = len(grup)
    context = {'grup': grup, 'latest_question_list': latest_question_list, 'count': count}
    return render(request, 'quiz/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'quiz/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'quiz/results.html', {'question': question})


def respond(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'quiz/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('quiz'))

quiz/templates/quiz/detail.html
{% extends 'main/base.html' %}
{% block content %}

<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'quiz:respond' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px; background-color: orange" value="Respond">
</form>


<div class="card-columns" style="padding: 10px; margin: 20px;"></div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

{% endblock %}

quiz/templates/quiz/index.html
{% extends 'main/base.html' %}
{% load static %}


<html lang="en">
{% block content %}
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataFlair discussion quiz</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>
    <style>
        .box{
            border: 4px solid black;
            margin: 0 auto;
        }
    </style>

</head>



<body>

        <h2 class="jumbotron">
            Currently active quizzes: {{count}}
            <form method="POST" class="from-group">
                {% csrf_token %}
            </form>
        </h2>
            <div class="card-columns" style="padding: 10px; margin: 20px;"></div>

            {%for g in grup %}
                <div class="card box container">
                        <br>
                        <h5 class="card-title">

                            <a><h3>{{g.name}}</h3></a>
                            </h5>
                {%for question in latest_question_list%}
                    {% if question.group == g %}

                                <h3 class="jumbotron">
                                     Quiz: {{question.question_text }}<br>
                                     <button class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px; background-color: orange;">
                                        <a href="{% url 'quiz:detail' question.id %}">Take quiz</a>
                                    </button>

                                    {% if user.is_superuser %}
                                    <button class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px; background-color: orange">
                                        <a href="{% url 'quiz:results' question.id %}">View Results</a>
                                    </button>
                                    {% endif %}

                                    <form method="POST" class="from-group">
                                        {% csrf_token %}

                                    </form> </h3>



                            {%endif%}

                <br>


            {%endfor%}
                    </div>
        <br>
        {%endfor%}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
{% endblock %}
</html>

quiz/templates/quiz/results.html
{% extends 'main/base.html' %}
{% load static %}


<html lang="en">
{% block content %}
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataFlair discussion quiz</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>
    <style>
        .box{
            border: 4px solid black;
            margin: 0 auto;
        }
    </style>

</head>



<body>

        <h2 class="jumbotron">
            <form method="POST" class="from-group">
                <h1>{{ question.question_text }}</h1>

                <ul>
                {% for choice in question.choice_set.all %}
                    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                {% endfor %}
                </ul>
                <button class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px; background-color: orange">
                    <a href="{% url 'quiz' %}">Back</a>
                </button>

            </form>
        </h2>
            <div class="card-columns" style="padding: 10px; margin: 20px;"></div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
{% endblock %}
</html>